/**
* Generated by go-doudou v2.5.13.
* Don't edit!
 */
package httpsrv

import (
	"net/http"

	"github.com/unionj-cloud/go-doudou/v2/framework"
	"github.com/unionj-cloud/go-doudou/v2/framework/rest"
)

type DoudouHandler interface {
	PostUser(w http.ResponseWriter, r *http.Request)
	PutUser(w http.ResponseWriter, r *http.Request)
	DeleteUser(w http.ResponseWriter, r *http.Request)
	GetUsers(w http.ResponseWriter, r *http.Request)
}

func Routes(handler DoudouHandler) []rest.Route {
	return []rest.Route{
		{
			Name:        "PostUser",
			Method:      "POST",
			Pattern:     "/user",
			HandlerFunc: handler.PostUser,
		},
		{
			Name:        "PutUser",
			Method:      "PUT",
			Pattern:     "/user",
			HandlerFunc: handler.PutUser,
		},
		{
			Name:        "DeleteUser",
			Method:      "DELETE",
			Pattern:     "/user",
			HandlerFunc: handler.DeleteUser,
		},
		{
			Name:        "GetUsers",
			Method:      "GET",
			Pattern:     "/users",
			HandlerFunc: handler.GetUsers,
		},
	}
}

var RouteAnnotationStore = framework.AnnotationStore{
	"PostUser": {
		{
			Name: "@role",
			Params: []string{
				"admin",
			},
		},
	},
}

func init() {
	framework.RegisterAnnotationStore(RouteAnnotationStore)
}
